// 8 - Frameworks/SvelteJs/src/App.svelte
<script>
    let tasks = [];

    const handleSubmit = (event) => {
        event.preventDefault();
        const newtask = event.target.newTask.value;

        if (newtask) {
            tasks.push(newtask)
            tasks = tasks
        } else {
            console.log("Empty Task");
        }
    };
</script>

<main>
    <h1>TODO List</h1>
    <form on:submit={handleSubmit}>
        <input type="text" placeholder="New Task" name="newTask" />
        <input type="submit" />
    </form>

    <h2>Tasks List</h2>
    <ul>
        {#each tasks as task}
            <li>{task}</li>
        {/each}
    </ul>
</main>

// 8 - Frameworks/VueJs/src/App.vue
<script setup>
</script>

<template>
    <body>
        <div id="app">
            <h1>TODO List</h1>
            <form @submit.prevent="handleSubmit">
                <input type="text" placeholder="New Task" v-model="newTask" />
                <input type="submit" />
            </form>
            <h2>Tasks List</h2>
            <ul>
                <li v-for="task in taskList">{{ task }}</li>
            </ul>
        </div>
    </body>
</template>

<script>
export default {
    name: "App",
    data() {
        return {
            taskList: [],
            newTask: "",
        };
    },
    methods: {
        renderList() {
            map = this.taskList.map((element) => {
                return element;
            });
        },
        handleSubmit() {
            if (this.newTask) {
                this.taskList.push(this.newTask);
            } else {
                console.log("Empty Task");
            }
        },
    },
};
</script>
