// 8 - Frameworks/VueJs/src/App.vue
<script setup>
</script>

<template>
    <body>
        <div id="app">
            <h1>TODO List</h1>
            <form @submit.prevent="handleSubmit">
                <input type="text" placeholder="New Task" v-model="newTask" />
                <input type="submit" />
            </form>
            <h2>Tasks List</h2>
            <ul>
                <li v-for="task in taskList">{{ task }}</li>
            </ul>
        </div>
    </body>
</template>

<script>
export default {
    name: "App",
    data() {
        return {
            taskList: [],
            newTask: "",
        };
    },
    methods: {
        renderList() {
            map = this.taskList.map((element) => {
                return element;
            });
        },
        handleSubmit() {
            if (this.newTask) {
                this.taskList.push(this.newTask);
            } else {
                console.log("Empty Task");
            }
        },
    },
};
</script>

// 8 - Frameworks/AngularJs/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterOutlet } from '@angular/router';
import { TaskListComponent } from './task-list/task-list.component';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, RouterOutlet, TaskListComponent, FormsModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})

export class AppComponent {
 
  newtask = ''
  tasks: {name: string, id: number}[] = []


  handleSubmit(){

    if (this.newtask){
        let index = this.tasks.length
        const newtask =  {name: this.newtask , id: index}
        this.tasks.push(newtask)
    }
    else{
      console.log('Empty Task')
    }
  }
}

<h1>TODO List</h1>

<form (submit)="handleSubmit()">
  <input name="newtask" type="text" placeholder="New Task" [(ngModel)]="newtask">
  <input type="Submit">
</form>

<h2>Task List</h2>
<app-task-list [tasklist] = "tasks"></app-task-list>

<router-outlet></router-outlet>
